
trigger:
- master

pool:
  default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'npm install'


- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'npm run build.azure'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/build'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    # Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'quizapp'
    publishLocation: 'Container'